"""Render the README chart and a markdown status block from the warehouse.

Run after every scheduled ingest so the repository's front page reflects the data
that is actually in the warehouse, not the data that was there when the README was
written by hand.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from pipeline import warehouse  # noqa: E402
from pipeline.config import REPORTS_DIR  # noqa: E402

# Colour-blind-safe pairing, distinguishable in greyscale.
# Suppress matplotlib's CreationDate stamp: without this an unchanged chart
# still renders to different bytes, so the daily job would commit both PNGs
# every morning forever whether or not the data moved.
PNG_METADATA = {"Software": None, "Creation Time": None}

WARM = "#D55E00"
COOL = "#0072B2"


def chart_diurnal_range(con, path: Path) -> None:
    """Diurnal range by city: the clearest maritime-versus-continental signal here."""
    rows = con.execute(
        """
        SELECT city_name, country, avg_diurnal_range, avg_temp_mean
        FROM gold_city_summary
        ORDER BY avg_diurnal_range
        """
    ).fetchall()
    if not rows:
        return

    labels = [f"{r[0]} ({r[1]})" for r in rows]
    values = [r[2] for r in rows]
    means = [r[3] for r in rows]

    fig, ax = plt.subplots(figsize=(8, 5))
    norm = plt.Normalize(min(means), max(means))
    colours = [plt.cm.coolwarm(norm(m)) for m in means]
    bars = ax.barh(labels, values, color=colours, edgecolor="white")
    ax.bar_label(bars, fmt="%.1f", padding=3, fontsize=8)

    ax.set_xlabel("mean daily temperature range (°C)")
    ax.set_title("Diurnal temperature range by city")
    ax.grid(axis="x", alpha=0.3)
    ax.set_axisbelow(True)
    sm = plt.cm.ScalarMappable(cmap="coolwarm", norm=norm)
    fig.colorbar(sm, ax=ax, label="mean temperature (°C)")
    fig.tight_layout()
    fig.savefig(path, dpi=160, metadata=PNG_METADATA)
    plt.close(fig)


def chart_monthly_means(con, path: Path) -> None:
    rows = con.execute(
        """
        SELECT city_name, month, avg_temp_mean
        FROM gold_monthly_city
        ORDER BY city_name, month
        """
    ).fetchall()
    if not rows:
        return

    series: dict[str, tuple[list, list]] = {}
    for city, month, temp in rows:
        xs, ys = series.setdefault(city, ([], []))
        xs.append(month)
        ys.append(temp)

    fig, ax = plt.subplots(figsize=(9, 5))
    for city, (xs, ys) in sorted(series.items()):
        ax.plot(xs, ys, marker="o", linewidth=1.6, label=city)
    ax.set_ylabel("mean temperature (°C)")
    ax.set_title("Monthly mean temperature by city")
    ax.grid(alpha=0.3)
    ax.set_axisbelow(True)
    ax.legend(fontsize=8, ncol=2, frameon=False)
    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(path, dpi=160, metadata=PNG_METADATA)
    plt.close(fig)


def status_markdown(con) -> str:
    latest = warehouse.latest_date(con)
    rows = con.execute("SELECT count(*) FROM fact_daily_weather").fetchone()[0]
    cities = con.execute("SELECT count(*) FROM dim_city").fetchone()[0]
    last_runs = con.execute(
        """
        SELECT started_at, status, rows_loaded, quality_passed
        FROM run_log ORDER BY started_at DESC LIMIT 5
        """
    ).fetchall()

    lines = [
        "<!-- generated by scripts/make_report.py -->",
        f"**Rows:** {rows:,} · **Cities:** {cities} · **Latest observation:** {latest}",
        "",
        "| Run started | Status | Rows | Quality |",
        "|---|---|---|---|",
    ]
    for started, status, loaded, passed in last_runs:
        mark = "pass" if passed else "**FAIL**"
        lines.append(f"| {started:%Y-%m-%d %H:%M} | {status} | {loaded} | {mark} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    con = warehouse.connect()
    chart_diurnal_range(con, REPORTS_DIR / "diurnal_range.png")
    chart_monthly_means(con, REPORTS_DIR / "monthly_means.png")
    (REPORTS_DIR / "status.md").write_text(status_markdown(con), encoding="utf-8")
    con.close()
    print(f"Wrote charts and status to {REPORTS_DIR}")


if __name__ == "__main__":
    main()
